# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arbeit Engenharia
email: contato@arbeit.eng.br
description: > # this means to ignore newlines until "baseurl:"
  Arbeit Engenharia
baseurl: # the subpath of your site, e.g. /blog
url: "http://arbeit.eng.br" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
# twitter_username: SBootstrap
# github_username:  BlackrockDigital
facebook_username: arbeitengenharia
instagram_username: arbeitengenharia
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Whatsapp
whatsapp_number: 554799541738
whatsapp_display_number: (47) 99954-1738

# Address information
# address_street: 3034 Melrose Place
address_city: Blumenau
address_state: SC
address_zip: 89000-000

# Build settings
markdown: kramdown

# Site Colors
grey: 444445
white: ffffff
yellow: f8b816
